### ISSUE TITLE
Local files support

### ISSUE THREAD

**Issue by widepeepoclap** [davidzeng0/yasha#3]
Hello,
I have a sound pad bot that plays a lot of audio files directly from disk to reduce load times. Is it possible to implement local files support or is there already a way to do it?
Thank you!

**Comment by davidzeng0** [comment]
There is currently no way to play directly from the disk, however you can set up an http server to serve those files and use a network FileTrack (see docs/FileTrack.md)

**Comment by davidzeng0** [comment]
If this is something you need then I can work on this issue

**Comment by widepeepoclap** [comment]
Was thinking about doing the same thing after making this issue. I believe that should work, but I'd love to see it natively supported in the future.
I deeply appreciate your efforts on this perfect project, thanks a lot!

**Comment by davidzeng0** [comment]
May I know why you are using this as opposed to lavaplayer (lavalink)?

**Comment by widepeepoclap** [comment]
Lavalink has this problem where the track would start playing briefly before the bot becomes fully connected since it doesn't emit a ready event. Sometimes it just stops sending the audio out of nowhere. I've tried other packages like djs/opus and they all cause memory leaks and fragmentation, and have inferior audio quality.

**Comment by davidzeng0** [comment]
See docs/FileTrack.md on how to use it

For security purposes, you may want to prevent users from attempting to play local files on your system if you allow them to play from any arbitrary url
```js
if(track.isLocalFile) return;
```

**Comment by davidzeng0** [comment]
I forgot to mention that local file support is added, let me know if you have any issues

**Comment by widepeepoclap** [comment]
I've been able to run it perfectly on local Ubuntu 20 but on Ubuntu 18 I'm getting this error for some reason.. ` [Error: Invalid data found when processing input]`
It's obviously related to ffmpeg because I couldn't install these packages (libavcodec58 libavformat58 libavutil56 libavfilter7 libswresample3) for sange since they're not available on bionic. I've also built ffmpeg from source but it still didn't help.
I can't update my vps to ubuntu 20 at the moment. Should I just dockerize everything or is there something I can do to get it working on bionic?

**Comment by davidzeng0** [comment]
I don't have experience with docker. Could you paste the error message from building ffmpeg from source?

**Comment by davidzeng0** [comment]
Also if your bot serves many people, its recommended to install ffmpeg from source to avoid the infinite loop problem
The packages are probably just outdated on Ubuntu 18 so if you type out most of the name (e.g sudo apt install libavfilter) and then spam tab key it will show up with the version that's available

**Comment by davidzeng0** [comment]
Another thing is it may be required to update the npm packages via `npm update`

**Comment by widepeepoclap** [comment]
> Could you paste the error message from building ffmpeg from source?

I didn't get any errors from that, the error was emitted from the TrackPlayer instance after calling start().
Anyways, the problem was that I installed ffmpeg libraries then built if from source on top.
Everything is working perfectly, as well as playing local files. Thank you a lot.

**Comment by davidzeng0** [comment]
No problem 👍
